baseURL = "https://EspirituJustin.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Espiritu.L.Justin"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Justin L. Espiritu"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:espiritu.l.justin@gmail.com"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/JuicyJuice1100"

    [[params.links]]
        icon = "linkedin"
        title = "linkedin"
        url = "https://www.linkedin.com/in/justin-espiritu-b4a277138/"
      